### PR TITLE
Update dependencies to Python3.9+ and freesasa to 2.2.1

### PR DESCRIPTION
**Pull request by amjjbonvin**
With the old 2.1.0 freesasa version installation fails because of a compiler issue (a problem noticed also for haddock3 by Vlad). Updating to 2.2.1 makes it work.

### CODE REVIEW

**Review by rvhonorato — CHANGES_REQUESTED** [review]
This change breaks the macos installation:

https://github.com/haddocking/prodigy/actions/runs/7035702037/job/19178036334?pr=29

**Comment by rvhonorato** [comment]
The test is showing it, see my message above

**Comment by amjjbonvin** [comment]
The motivation is that with freesasa2.1.1 the installation fails. Again an issue reported by Vlad when installing haddock3. Has to do the latest compiler versions. freesasa2.2.1 solves the issue and the installation works fine.

On my mac poetry works fine and the unit tests are passing. The failure in the actions above are related to poetry it seems. 
Seems a python version issue. Updating the requirements to use python >=3.9 makes the test pass!

And I also removed the poetry.lock file from the repo as it should be created when running `poetry install`

**Comment by rvhonorato** [comment]
> The motivation is that with freesasa2.1.1 the installation fails. Again an issue reported by Vlad when installing haddock3. Has to do with the latest compiler versions. freesasa2.2.1 solves the issue and the installation works fine.

I'm not aware of this, could you please link this discussion/issue here?

**Comment by amjjbonvin** [comment]
This was a discussion in our slack channel - we don't have an issue about it as far as I can see.  In the haddock3 requirements we have freesasa==2.2.0.post3  as requirement. Should probably update to 2.2.1

This was only happening on a very recent Ubuntu version. And on my mac which is freshly installed and thus has a recent compiler version.

**Pull request merged**
